[package]
name = "source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
soapysdr = "0.3.2"
num-complex = "0.4.0"
zmq = "0.9"